// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:centero/secrets.dart';
import 'package:firebase_core/firebase_core.dart';

const firebaseOptionsWeb = FirebaseOptions(
  apiKey: centeroFirebaseApiKey,
  appId: centeroFirebaseAppId,
  messagingSenderId: centeroFirebaseMessagingSenderId,
  projectId: centeroFirebaseProjectId,
  authDomain: centeroFirebaseAuthDomain,
  databaseURL: centeroFirebaseDatabaseURL,
  storageBucket: centeroFirebaseStorageBucket,
);
